from django.urls import path
from customer_panel import views
from customer_panel import nexadash_views
app_name='nexadash'
urlpatterns = [
    path('entry/', views.entry, name="entry"),
    path('accounts/select/', views.account_select, name="account-select"),
    path('accounts/switch/<uuid:account_id>/', views.account_switch, name="account-switch"),
    path('domains/', views.domains, name="domains"),
    path('domains/renew/', views.domain_renewals, name="domain-renewals"),
    path('domains/register/', views.domain_register, name="domain-register"),
    path('domains/checker/', views.domain_checker, name="domain-checker"),
    path('domains/transfer/', views.domain_transfer, name="domain-transfer"),
    path('domains/whois/', views.whois_lookup, name="whois"),
    path('services/', views.services, name="services"),
    path('services/addons/', views.service_addons, name="service-addons"),
    path('',nexadash_views.index,name="index"),
    path('index/',nexadash_views.index,name="index"),
    path('crm/',nexadash_views.crm,name="crm"),
    path('finance/',nexadash_views.finance,name="finance"),
    path('analytics/',nexadash_views.analytics,name="analytics"),
    path('sales/',nexadash_views.sales,name="sales"),
    path('ecommerce/',nexadash_views.ecommerce,name="ecommerce"),
    path('course/',nexadash_views.course,name="course"),
    path('medical/',nexadash_views.medical,name="medical"),

    path('overview/',nexadash_views.overview,name="overview"),
    path('projects/',nexadash_views.projects,name="projects"),
    path('projects-details/',nexadash_views.projects_details,name="projects-details"),
    path('campaigns/',nexadash_views.campaigns,name="campaigns"),
    path('documents/',nexadash_views.documents,name="documents"),
    path('followers/',nexadash_views.followers,name="followers"),
    path('activity/',nexadash_views.activity,name="activity"),

    path('account-overview/',nexadash_views.account_overview,name="account-overview"),
    path('account-settings/',nexadash_views.account_settings,name="account-settings"),
    path('account-security/',nexadash_views.account_security,name="account-security"),
    path('account-login-security/',nexadash_views.account_login_security,name="account-login-security"),
    path('account-change-password/',nexadash_views.account_change_password,name="account-change-password"),
    path('account-activity/',nexadash_views.account_activity,name="account-activity"),
    path('billing/',nexadash_views.billing,name="billing"),
    path('statements/',nexadash_views.statements,name="statements"),
    path('add-funds/', nexadash_views.add_funds, name="add-funds"),
    path('payment-methods/', nexadash_views.payment_methods, name="payment-methods"),
    path('payment-methods/billing/', nexadash_views.payment_methods_billing, name="payment-methods-billing"),
    path('payment-methods/add/', nexadash_views.payment_method_add, name="payment-methods-add"),
    path('account/users/', nexadash_views.user_management, name="user-management"),
    path('account/contacts/', nexadash_views.contacts, name="contacts"),
    path('account/email-history/', nexadash_views.email_history, name="email-history"),
    path('support/new-ticket/', nexadash_views.support_new_ticket, name="support-new-ticket"),
    path('support/new-ticket/<slug:dept_slug>/', nexadash_views.support_new_ticket_department, name="support-new-ticket-department"),
    path('support/tickets/', nexadash_views.support_tickets, name="support-tickets"),
    path('support/announcements/', nexadash_views.support_announcements, name="support-announcements"),
    path('receipts/<int:receipt_id>/invoice/', nexadash_views.receipt_invoice, name="receipt-invoice"),
    path('referrals/',nexadash_views.referrals,name="referrals"),
    path('api-keys/',nexadash_views.api_keys,name="api-keys"),
    path('logs/',nexadash_views.logs,name="logs"),

    path('content/',nexadash_views.content,name="content"),
    path('add-content/',nexadash_views.add_content,name="add-content"),
    path('menu/',nexadash_views.menu,name="menu"),
    path('email-template/',nexadash_views.email_template,name="email-template"),
    path('add-email/',nexadash_views.add_email,name="add-email"),
    path('blog/',nexadash_views.blog,name="blog"),
    path('add-blog/',nexadash_views.add_blog,name="add-blog"),
    path('blog-category/',nexadash_views.blog_category,name="blog-category"),
    
    path('auto-write/',nexadash_views.auto_write,name="auto-write"),
    path('scheduled/',nexadash_views.scheduled,name="scheduled"),
    path('repurpose/',nexadash_views.repurpose,name="repurpose"),
    path('rss/',nexadash_views.rss,name="rss"),
    path('chatbot/',nexadash_views.chatbot,name="chatbot"),
    path('fine-tune-models/',nexadash_views.fine_tune_models,name="fine-tune-models"),
    path('imports/',nexadash_views.imports,name="imports"),
    path('prompt/',nexadash_views.prompt,name="prompt"),
    path('setting/',nexadash_views.setting,name="setting"),

    path('chat/',nexadash_views.chat,name="chat"),
    path('app-profile-1/',nexadash_views.app_profile_1,name="app-profile-1"),
    path('app-profile-2/',nexadash_views.app_profile_2,name="app-profile-2"),
    path('edit-profile/',nexadash_views.edit_profile,name="edit-profile"),
    path('post-details/',nexadash_views.post_details,name="post-details"),

    path('email-compose/',nexadash_views.email_compose,name="email-compose"),
    path('email-inbox/',nexadash_views.email_inbox,name="email-inbox"),
    path('email-read/',nexadash_views.email_read,name="email-read"),

    path('app-calendar/',nexadash_views.app_calendar,name="app-calendar"),

    path('category-table/',nexadash_views.category_table,name="category-table"),
    path('add-category/',nexadash_views.add_category,name="add-category"),
    path('edit-category/',nexadash_views.edit_category,name="edit-category"),
    path('product-table/',nexadash_views.product_table,name="product-table"),
    path('add-product/',nexadash_views.add_product,name="add-product"),
    path('edit-product/',nexadash_views.edit_product,name="edit-product"),
    path('ecom-product-grid/',nexadash_views.ecom_product_grid,name="ecom-product-grid"),
    path('ecom-product-list/',nexadash_views.ecom_product_list,name="ecom-product-list"),
    path('ecom-product-detail/',nexadash_views.ecom_product_detail,name="ecom-product-detail"),
    path('ecom-product-order/',nexadash_views.ecom_product_order,name="ecom-product-order"),
    path('ecom-checkout/',nexadash_views.ecom_checkout,name="ecom-checkout"),
    path('ecom-invoice/',nexadash_views.ecom_invoice,name="ecom-invoice"),
    path('ecom-customers/',nexadash_views.ecom_customers,name="ecom-customers"),

    path('ui-accordion/',nexadash_views.ui_accordion,name="ui-accordion"),
    path('ui-alert/',nexadash_views.ui_alert,name="ui-alert"),
    path('ui-badge/',nexadash_views.ui_badge,name="ui-badge"),
    path('ui-button/',nexadash_views.ui_button,name="ui-button"),
    path('ui-modal/',nexadash_views.ui_modal,name="ui-modal"),
    path('ui-button-group/',nexadash_views.ui_button_group,name="ui-button-group"),
    path('ui-list-group/',nexadash_views.ui_list_group,name="ui-list-group"),
    path('ui-card/',nexadash_views.ui_card,name="ui-card"),
    path('ui-carousel/',nexadash_views.ui_carousel,name="ui-carousel"),
    path('ui-dropdown/',nexadash_views.ui_dropdown,name="ui-dropdown"),
    path('ui-offcanvas/',nexadash_views.ui_offcanvas,name="ui-offcanvas"),
    path('ui-popover/',nexadash_views.ui_popover,name="ui-popover"),
    path('ui-breadcrumb/',nexadash_views.ui_breadcrumb,name="ui-breadcrumb"),
    path('ui-progressbar/',nexadash_views.ui_progressbar,name="ui-progressbar"),
    path('ui-tab/',nexadash_views.ui_tab,name="ui-tab"),
    path('ui-media-object/',nexadash_views.ui_media_object,name="ui-media-object"),
    path('ui-toasts/',nexadash_views.ui_toasts,name="ui-toasts"),
    path('ui-spinners/',nexadash_views.ui_spinners,name="ui-spinners"),
    path('ui-scrollspy/',nexadash_views.ui_scrollspy,name="ui-scrollspy"),
    path('ui-range-slider/',nexadash_views.ui_range_slider,name="ui-range-slider"),
    path('ui-placeholder/',nexadash_views.ui_placeholder,name="ui-placeholder"),
    path('ui-object-fit/',nexadash_views.ui_object_fit,name="ui-object-fit"),
    path('ui-colors/',nexadash_views.ui_colors,name="ui-colors"),
    path('ui-navbar/',nexadash_views.ui_navbar,name="ui-navbar"),
    path('ui-typography/',nexadash_views.ui_typography,name="ui-typography"),
    path('ui-pagination/',nexadash_views.ui_pagination,name="ui-pagination"),
    path('ui-grid/',nexadash_views.ui_grid,name="ui-grid"),

    path('uc-select2/',nexadash_views.uc_select2,name="uc-select2"),
    path('uc-nestable/',nexadash_views.uc_nestable,name="uc-nestable"),
    path('uc-noui-slider/',nexadash_views.uc_noui_slider,name="uc-noui-slider"),
    path('uc-sweetalert/',nexadash_views.uc_sweetalert,name="uc-sweetalert"),
    path('uc-toastr/',nexadash_views.uc_toastr,name="uc-toastr"),
    path('map-jqvmap/',nexadash_views.map_jqvmap,name="map-jqvmap"),
    path('uc-lightgallery/',nexadash_views.uc_lightgallery,name="uc-lightgallery"),

    path('chart-flot/',nexadash_views.chart_flot,name="chart-flot"),
    path('chart-morris/',nexadash_views.chart_morris,name="chart-morris"),
    path('chart-chartjs/',nexadash_views.chart_chartjs,name="chart-chartjs"),
    path('chart-chartist/',nexadash_views.chart_chartist,name="chart-chartist"),
    path('chart-sparkline/',nexadash_views.chart_sparkline,name="chart-sparkline"),
    path('chart-peity/',nexadash_views.chart_peity,name="chart-peity"),

    path('widget-basic/',nexadash_views.widget_basic,name="widget-basic"),

    path('form-element/',nexadash_views.form_element,name="form-element"),
    path('form-wizard/',nexadash_views.form_wizard,name="form-wizard"),
    path('form-editor/',nexadash_views.form_editor,name="form-editor"),
    path('form-pickers/',nexadash_views.form_pickers,name="form-pickers"),
    path('form-validation/',nexadash_views.form_validation,name="form-validation"),

    path('table-bootstrap-basic/',nexadash_views.table_bootstrap_basic,name="table-bootstrap-basic"),
    path('table-datatable-basic/',nexadash_views.table_datatable_basic,name="table-datatable-basic"),

    path('page-empty/',nexadash_views.page_empty,name="page-empty"),
    path('page-error-400/',nexadash_views.page_error_400,name="page-error-400"),
    path('page-error-403/',nexadash_views.page_error_403,name="page-error-403"),
    path('page-error-404/',nexadash_views.page_error_404,name="page-error-404"),
    path('page-error-500/',nexadash_views.page_error_500,name="page-error-500"),
    path('page-error-503/',nexadash_views.page_error_503,name="page-error-503"),
]
