# Generated by Django 5.2.1 on 2026-05-02 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
                ('renewal_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('redemption', 'Kurtarma Donemi'), ('expired', 'Suresi Doldu'), ('pending', 'Beklemede')], default='active', max_length=24)),
                ('ssl_status', models.CharField(choices=[('active', 'Gecerli SSL Sertifikasi'), ('inactive', 'SSL Sertifikasi Tespit Edilemedi'), ('domain_inactive', 'Domain Aktif Degil')], default='inactive', max_length=24)),
                ('registrar', models.CharField(blank=True, max_length=120)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='customer_panel.customeraccount')),
            ],
            options={
                'ordering': ['renewal_date', 'name'],
                'unique_together': {('account', 'name')},
            },
        ),
    ]
