# Generated by Django 5.2.1 on 2026-05-02 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_panel', '0002_customerdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('hosting', 'Hosting'), ('vps_vds', 'VPS / VDS'), ('ssl', 'SSL Sertifikasi'), ('email', 'E-Mail Hizmeti')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('period', models.CharField(default='12 Ay', max_length=64)),
                ('renewal_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('pending', 'Beklemede'), ('suspended', 'Durduruldu')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customer_panel.customeraccount')),
            ],
            options={
                'ordering': ['renewal_date', 'name'],
            },
        ),
    ]
