# Generated by Django 5.2.1 on 2026-05-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sso_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sso_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
